### ISSUE TITLE
How does manual matching with multiple emission and generation entries work?

### ISSUE THREAD

**Issue by madsnedergaard** [w-flo/eu-emission-factors#5]
Hey, figured it would be best to create a new issue here to discuss this particular topic :)

I've been reading through the Rust code, but since it's not my speciality (in any way 😅), I'm struggling a bit with understanding how your manual matching works for the particular case where there are multiple names (separated by `|`) for both generation and emission. 

How do you know what generation unit belongs to which emissions entry?

As an example, I am looking at Karlshamnsverket in Sweden. Your CSV row looks like this:
Generation | Emission
-- | --
Karlshamn G1 \|Karlshamn G2\|Karlshamn G3 | id:10-563-005832-2004:138\|id:10-563-005762-04:241

But the 2 emission entries have very different values:

Name | id (combined) | verified emissions 2023
-- | -- | --
Karlshamnsverket | 10-563-005832-2004:138 | 12044
Karlshamnsverkets gasturbinanläggning | 10-563-005762-04:241 | 207

And the entries from ENTSO-E:

Name | Generation in MWh
-- | -- 
Karlshamn G1 | 19665.13
Karlshamn G3 | 13151.13

According to https://en.wikipedia.org/wiki/Karlshamn_Power_Station I would expect both should map to the`10-563-005832-2004:138` (and not the gas turbine thing), but if you already have an approach of how to map these it would be great :)

**Comment by w-flo** [comment]
Hi! Thanks for opening this issue :-)

Generally, the "|" simply combines (by adding up) all the generation units and emission entries listed in that line in the CSV.

So in this case, it would sum the energy generated by these 3 Karlshamn units, and then sum both emission entries, and then divide the latter sum by the former sum to calculate an emission factor for that line in the CSV file. So the different generation units are not actually matched to individual "emission units" in that line, it's all just lumped together.

This is often useful for generation units, because quite often there are N generation units for 1 emission entry. On top of that, I sometimes used it for the emission data if I was unsure which generation unit(s) of a power plant map(s) to which emission record of the power plant if there are multiple to choose from. So sometimes it's just "take all the emission records that sound like they belong to this power plant, add them together and see if the result seems to be in a range that should be expected for this kind of fuel".

As you point out, this was probably not the right approach in this case, so it's an error in my manual matches file: It looks like the "gasturbinenanläggning" is not actually one of the G1, G2 or G3 units (which are oil-powered), but a separate gas-powered unit which does not report to ENTSO-E (?). If so, that :241 entry should be dropped from the file.

I should probably investigate other cases with "combined emission data" like this, e.g. ELEKTROWNIA KOZIENICE or Castejón. Maybe these are wrong, too, or maybe they can be improved (like multiple lines with 1 emission record each).

**Comment by madsnedergaard** [comment]
Sorry for the late reply here, and thanks for the detailed response :)
